# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Publish Docker

# 触发workflow的条件，
on:

# 只有master分支发生push事件时，才会触发workflow
  push:
    branches: [ main ]
    
# jobs表示执行的一项或多项任务
jobs:
# 任务的job_id，具体名称自定义，这里build代表打包
  build:
# runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    runs-on: ubuntu-latest
# 用于配置当前workflow的参数
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
# steps字段指定每个job的运行步骤，可以包含一个或多个步骤，每个步骤都可以配置指定字段
    steps:
    # 切代码到 runner
    - name: Checkout
      uses: actions/checkout@v2  
      
    - name: Install dependencies  # 第二步，安装依赖
      run: npm install
      
    - name: Build              # 第三步，打包代码
      run: npm run build --if-present

#打包镜像推送私有容器镜像服务
    - name: Build the Docker image
    run: |
    docker login -u lisi -p 123456 106.74.154.45:8081
    docker build . --file Dockerfile --tag vuedemox:$(date +%s)
    #docker build -t vuedemox:v1 .
    docker tag vuedemox:v1 106.74.154.45:8081/vuedemox:v1
    docker push 106.74.154.45:8081/vuedemox:v1
